name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: npm ci
      working-directory: ./fe
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: ./fe
      
    - name: Run Playwright tests
      run: npx playwright test
      working-directory: ./fe
      env:
        CI: true
        
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: fe/playwright-report/
        retention-days: 30
        
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: fe/test-results/
        retention-days: 30